### ISSUE TITLE
Not working on Feather M0 Adalogger

### ISSUE THREAD

**Issue by jessetmoody** [charkster/samd21-gpio_high_and_low_durations#1]
Was glad to find this, but it's not working for me and I'm not sure why.

Changed PIN to 6 (PA20 on Feather M0 Adalogger) and inputted square wave (3.3V and 0V, 20us period, 50% duty cycle, therefore 10us HIGH pulses), but upon hitting Enter in serial monitor, the high/low pulse durations are both always 0. Tried debugging using a JLINK to Feather's SWD pins and placed breakpoint in TC4_Handler. The ISR was never hit. Tried inputting signal to every single IO pin available to no avail.

Were you able to get this code working @charkster ? Do you have any ideas as to what my issue could be? Any help is appreciated!

**Comment by charkster** [comment]
@jessetmoody For PA20, use #define Pin 20
Also on line 50 as Pin 20 is even, use "PORT_PMUX_PMUXE_A" instead of "PORT_PMUX_PMUXO_A" (this is what the comment on line 49 is trying to remind). 
I believe those would be the only changes needed (sorry it has been a while since I last did SAMD21 C programming).

**Comment by jessetmoody** [comment]
I did need to change PORT_PMUX_PMUXO_A to PORT_PMUX_PMUXE_A. **I also had to change the external interrupt used since PA20 uses ext int 4.** Doing that fixed my issue and I can now use this with my Feather M0! Just leaving this here for any other poor wayfaring strangers.

Full code attached.
[pulseCounterFeatherM0.txt](https://github.com/user-attachments/files/15822128/pulseCounterFeatherM0.txt)

**Comment by charkster** [comment]
@jessetmoody Thanks for the update and documenting the additional change needed for PA20.

**Comment by charkster** [comment]
I took this from your attached code... as the change for the external interrupt configuration.

```
EIC->EVCTRL.reg    = EIC_EVCTRL_EXTINTEO4;   // Enable event output on external interr
EIC->CONFIG[0].reg = EIC_CONFIG_SENSE4_HIGH; // Set event detect a high (config 0, #4 is ext interrupt 4 for pin 6 (PA20))
EIC->INTENCLR.reg  = EIC_INTENCLR_EXTINT4;   // Clear the interrupt flag on channel 4
EIC->CTRL.reg      = EIC_CTRL_ENABLE;        // Enable EIC peripheral
while (EIC->STATUS.bit.SYNCBUSY);            // Wait for synchronization
```
